# Generated by Django 2.2.7 on 2019-12-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(),
        ),
    ]
