# Generated by Django 2.2.7 on 2019-12-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reader', '0002_auto_20191201_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
