# Generated by Django 2.2.7 on 2019-12-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reader', '0003_auto_20191201_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
